# Go 延迟函数

### 延迟函数调用

在Go中，一个函数调用可以跟在一个`defer`关键字后面，成为一个延迟函数调用（deferred function call），此`defer`关键字和此延迟函数调用一起形成一个延迟调用语句。和协程调用类似，被延迟的函数调用的所有返回值必须全部被舍弃。

当一个延迟调用语句被执行时，其中的延迟函数调用不会立即被执行，而是被推入由当前协程维护的一个延迟调用队列（一个后进先出队列）。当函数调用返回（此时可能尚未完全退出）并进入它的退出阶段后，所有在执行此函数调用的过程中已经被推入延迟调用队列的调用将被按照它们被推入的顺序逆序被弹出队列并执行，当所有这些延迟调用执行完毕后，此函数调用也就完全退出了。下面这个例子展示了如何使用延迟调用函数。

```go
package main

import "fmt"

func main() {
	defer fmt.Println("The third line.")
	defer fmt.Println("The second line.")
	fmt.Println("The first line.")
}
```

输出结果：

```
The first line.
The second line.
The third line.
```



下面是另一个略微复杂一点的使用了延迟调用的例子程序，此程序将按照自然数的顺序打印出0到9十个数字。

```go
package main

import "fmt"

func main() {
	defer fmt.Println("9")
	fmt.Println("0")
	defer fmt.Println("8")
	fmt.Println("1")
	if false {
		defer fmt.Println("not reachable")
	}
	defer func() {
		defer fmt.Println("7")
		fmt.Println("3")
		defer func() {
			fmt.Println("5")
			fmt.Println("6")
		}()
		fmt.Println("4")
	}()
	fmt.Println("2")
	return
	defer fmt.Println("not reachable")
}
```



延迟调用可以修改包含此延迟调用的最内层函数的返回值，一个例子：

```go
package main

import "fmt"

func Triple(n int) (r int) {
	defer func() {
		r += n // 修改返回值
	}()

	return n + n // <=> r = n + n; return
}

func main() {
	fmt.Println(Triple(5)) // 15
}
```



### 延迟函数调用的必要性和好处

延迟调用对于恐慌/恢复特性是必要的，可以帮助写出更整洁和更鲁棒的代码。



### 很多有返回值的内置函数是不能被延迟调用的

在Go中，自定义函数的调用的返回值都可以被舍弃，但是，大多数内置函数（除了`copy`和`recover`）的调用的返回值都不可以舍弃。另一方面，延迟函数调用的所有返回值必须都舍弃掉，所以很多内置函数是不能被延迟调用的。针对延迟调用有返回值内置函数的场景，如`append`，可以延迟调用一个调用了`append`函数的匿名函数来满足这个需求。

```go
package main

import "fmt"

func main() {
	s := []string{"a", "b", "c", "d"}
	defer fmt.Println(s) // [a x y d]
	// defer append(s[:1], "x", "y") // 编译错误
	defer func() {
		_ = append(s[:1], "x", "y")
	}()
}
```



### 协程和延迟调用的实参的估值时刻

延迟调用的实参是在此调用对应的延迟调用语句被执行时被估值的，或者说是在此延迟调用被推入延迟调用队列时被估值的，这些被估值的结果将在以后此延迟调用被执行的时候使用。匿名函数体内的表达式是在此函数被执行的时候才会被逐渐估值的，不管此函数是被普通调用还是延迟/协程调用。一个例子：

```go
// eval-moment.go
package main

import "fmt"

func main() {
	func() {
		var x = 0
		for i := 0; i < 3; i++ {
			defer fmt.Println("a:", i + x) // 被推入延迟调用队列时被估值
		}
		x = 10
	}()
	fmt.Println()
	func() {
		var x = 0
		for i := 0; i < 3; i++ {
			defer func() {
				fmt.Println("b:", i + x) // 匿名函数体内的表达式是在此函数被执行的时候才会被逐渐估值的
			}()
		}
		x = 10
	}()
}
```



使用不同版本的Go编译器运行（gotv是一个管理运行多个Go官方工具链版本的工具），将得到如下输出结果：

```
$ gotv 1.21. run eval-moment.go
[Run]: $HOME/.cache/gotv/tag_go1.21.8/bin/go run eval-moment.go
a: 2
a: 1
a: 0

b: 13
b: 13
b: 13
$ gotv 1.22. run eval-moment.go
[Run]: $HOME/.cache/gotv/tag_go1.22.1/bin/go run eval-moment.go
a: 2
a: 1
a: 0

b: 12
b: 11
b: 10
```



两次输出结果不一致是因为Go 1.22对`for`循环流程控制做出的语义修改而导致的代码行为变化。可以对第二个循环略加修改（使用两种方法），使得它和第一个循环打印出相同的结果。

```go
    for i := 0; i < 3; i++ {
        defer func(i int) {
            // 此i为形参i，非实参循环变量i。
            fmt.Println("b:", i)
        }(i)
    }
```

或者

```go
    for i := 0; i < 3; i++ {
        i := i // 在下面的调用中，左i遮挡了右i。
               // <=> var i = i
        defer func() {
            // 此i为上面的左i，非循环变量i。
            fmt.Println("b:", i)
        }()
    }
```



同样的估值时刻规则也适用于协程调用，下面这个例子程序将打印出`123 789`。

```go
package main

import "fmt"
import "time"

func main() {
	var a = 123
	go func(x int) {
		time.Sleep(time.Second)
		fmt.Println(x, a) // 123 789
	}(a)

	a = 789

	time.Sleep(2 * time.Second)
}
```



使用`time.Sleep`调用来做并发同步不是一个好的方法，如果上面这个程序运行在一个满负荷运行的电脑上，此程序可能在新启动的协程可能还未得到执行机会的时候就已经退出了。在正式的项目中应该使用并发同步技术来实现并发同步。



### 延迟调用的函数值的估值时刻

被延迟调用的函数值是在其调用被推入延迟调用队列之前被估值的，例如，下面这个例子将输出`false`。

```go
package main

import "fmt"

func main() {
	var f = func () {
		fmt.Println(false)
	}
	defer f()
	f = func () {
		fmt.Println(true)
	}
}
```



被延迟调用的函数值可能是一个nil函数值，此时将导致一个恐慌，恐慌产生在此延迟调用被执行而不是被推入延迟调用队列的时候。一个例子：

```go
package main

import "fmt"

func main() {
	defer fmt.Println("此行可以被执行到")
	var f func() // f == nil
	defer f()    // 将产生一个恐慌
	fmt.Println("此行可以被执行到")
	f = func() {} // 此行不会阻止恐慌产生
}
```



### 延迟方法调用的属主实参的估值时刻

延迟调用的实参也是在此调用被推入延迟调用队列时估值的，方法的属主实参也不例外。比如下面这个程序将打印出`1342`。

```go
package main

type T int

func (t T) M(n int) T {
  print(n)
  return t
}

func main() {
	var t T
	// t.M(1)是方法调用M(2)的属主实参，因此它将在M(2)调用被推入延迟调用队列时被估值。
	defer t.M(1).M(2)
	t.M(3).M(4)
}
```



### 延迟调用使得代码更简洁和鲁棒

```go
import "os"

func withoutDefers(filepath string, head, body []byte) error {
	f, err := os.Open(filepath)
	if err != nil {
		return err
	}

	_, err = f.Seek(16, 0)
	if err != nil {
		f.Close()
		return err
	}

	_, err = f.Write(head)
	if err != nil {
		f.Close()
		return err
	}

	_, err = f.Write(body)
	if err != nil {
		f.Close()
		return err
	}

	err = f.Sync()
	f.Close()
	return err
}

func withDefers(filepath string, head, body []byte) error {
	f, err := os.Open(filepath)
	if err != nil {
		return err
	}
	defer f.Close()

	_, err = f.Seek(16, 0)
	if err != nil {
		return err
	}

	_, err = f.Write(head)
	if err != nil {
		return err
	}

	_, err = f.Write(body)
	if err != nil {
		return err
	}

	return f.Sync()
}
```



第二个使用了延迟调用的函数简洁了些许，导致更少的bug，因为第一个函数中含有太多的`f.Close()`调用，从而有较高的几率漏掉其中一个。下面是另外一个延迟调用使得代码更鲁棒的例子。如果`doSomething`函数产生恐慌，则函数`f2`在退出时将导致互斥锁未解锁，所以函数`f1`更鲁棒。

```go
var m sync.Mutex

func f1() {
	m.Lock()
	defer m.Unlock()
	doSomething()
}

func f2() {
	m.Lock()
	doSomething()
	m.Unlock()
}
```



### 延迟调用可能会导致性能损失

延迟调用并非没有缺点，对于早于1.13版本的官方标准编译器来说，延迟调用将导致一些性能损失。从Go官方工具链1.13版本开始，官方标准编译器对一些常见的延迟调用场景做了很大的优化。因此，一般不必太在意延迟调用导致的性能损失。



### 延迟调用导致的暂时性内存泄露

较大的延迟调用队列可能会消耗很多内存，某些资源可能因为某些调用被延迟的太久而未能被及时释放导致暂时性内存泄漏。详情可以查询【Go 内存 - 内存泄漏】。
